server:
  port: 4444
eureka:
  client:
    service-url:
      defaultZone:http://localhost:1111/eureka/
spring:
  application:
    name: gateway
  profiles:
    active: rewritepath_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: rewritepath_route
          uri: http://httpbin.org:80
          predicates:
            - Path=/foo/**
          filters:
            - RewritePath=/foo/(?<segment>.*), /$\{segment}
  profiles: rewritepath_route




